modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "just_like_rays"
version = "${version}"
displayName = "Just Like Rays"
authors = "Teluri"
description = '''
Make light sources lit the environment in a more realistic way
'''
#logoFile = ""

[[dependencies.just_like_rays]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.just_like_rays]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.just_like_rays]]
modId = "cloth-config2"
mandatory = true
versionRange = "*"
ordering = "AFTER"
side = "CLIENT"